/**
 * Game engine — orchestrates a full Werewolf game by calling real LLMs.
 * Each player's speech, private reasoning, votes, and night actions are
 * generated by the model listed in their Player record.
 */

import type { GameEvent, Player, Role } from "./game-script"
import { callLLM, type Message } from "./llm"

// ── Types ──────────────────────────────────────────────────────────────────

interface GameState {
  alive: Set<string>
  round: number
  publicChat: Array<{ player: string; text: string }>
  seerKnowledge: Map<string, Role> // target id → role discovered
  lastDoctorProtected: string | null
  correctVotes: Map<string, number> // voter id → # of correct wolf votes
}

type SendFn = (event: GameEvent) => void

// ── Helpers ────────────────────────────────────────────────────────────────

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

function pname(id: string, players: Player[]) {
  return players.find((p) => p.id === id)?.name ?? id
}

function aliveList(
  players: Player[],
  alive: Set<string>,
  exclude: string[] = []
): string {
  return players
    .filter((p) => alive.has(p.id) && !exclude.includes(p.id))
    .map((p) => `${p.name} [id:${p.id}]`)
    .join(", ")
}

function checkWin(
  players: Player[],
  alive: Set<string>
): "wolves" | "villagers" | null {
  const liveWolves = players.filter(
    (p) => p.role === "werewolf" && alive.has(p.id)
  )
  const liveVillagers = players.filter(
    (p) => p.role !== "werewolf" && alive.has(p.id)
  )
  if (liveWolves.length === 0) return "villagers"
  if (liveWolves.length >= liveVillagers.length) return "wolves"
  return null
}

function tallyVotes(
  votes: Map<string, string>,
  alive: Set<string>
): string | null {
  const counts = new Map<string, number>()
  for (const target of votes.values()) {
    if (alive.has(target)) counts.set(target, (counts.get(target) ?? 0) + 1)
  }
  let best: string | null = null
  let max = 0
  for (const [id, n] of counts) {
    if (n > max) {
      max = n
      best = id
    }
  }
  return best
}

async function safeJSON(
  raw: string,
  fallback: Record<string, string>
): Promise<Record<string, string>> {
  try {
    return JSON.parse(raw)
  } catch {
    const m = raw.match(/\{[\s\S]*?\}/)
    if (m) {
      try {
        return JSON.parse(m[0])
      } catch { /* fall through */ }
    }
    return fallback
  }
}

// ── Prompts ────────────────────────────────────────────────────────────────

function buildSystemPrompt(player: Player, players: Player[]): string {
  let roleDesc: string
  switch (player.role) {
    case "werewolf": {
      const partners = players
        .filter((p) => p.role === "werewolf" && p.id !== player.id)
        .map((p) => p.name)
      const partnerStr =
        partners.length > 0
          ? ` Your wolf partner: ${partners.join(", ")}.`
          : " You are the lone wolf."
      roleDesc = `WEREWOLF.${partnerStr} Goal: avoid detection and eliminate villagers until wolves ≥ villagers.`
      break
    }
    case "seer":
      roleDesc =
        "SEER (Villager team). Each night you secretly investigate one player and learn their true role. Use that to guide the village without exposing yourself prematurely."
      break
    case "doctor":
      roleDesc =
        "DOCTOR (Villager team). Each night you secretly protect one player from wolf attack. You cannot protect the same player two nights in a row."
      break
    case "villager":
      roleDesc =
        "VILLAGER. No special power. Deduce who the wolves are from statements and voting patterns."
      break
  }

  return `You are ${player.name}, an AI playing Werewolf (Mafia).
YOUR ROLE: ${roleDesc}

RULES: Wolves win if wolves ≥ villagers. Villagers win if all wolves are eliminated.
Night: wolves kill, doctor protects, seer investigates (all secretly).
Day: everyone discusses. Vote: everyone votes to eliminate one player.

CRITICAL: Respond ONLY with valid JSON as specified. No markdown. No preamble.`
}

function chatLog(
  chat: Array<{ player: string; text: string }>,
  players: Player[]
) {
  return chat.length === 0
    ? "(no statements yet)"
    : chat.map((c) => `${pname(c.player, players)}: "${c.text}"`).join("\n")
}

// ── Night actions ─────────────────────────────────────────────────────────

async function wolfTurn(
  wolf: Player,
  partnerName: string | null,
  state: GameState,
  players: Player[],
  send: SendFn
): Promise<string> {
  const nonWolves = players.filter(
    (p) => p.role !== "werewolf" && state.alive.has(p.id)
  )
  const fallbackTarget = nonWolves[0].id

  const messages: Message[] = [
    { role: "system", content: buildSystemPrompt(wolf, players) },
    {
      role: "user",
      content: `NIGHT ${state.round} — WOLF KILL

${partnerName ? `Your wolf partner is ${partnerName}. Agree on a target.` : "You are the lone wolf."}
Eligible targets: ${nonWolves.map((p) => `${p.name} [id:${p.id}]`).join(", ")}

Public chat so far:
${chatLog(state.publicChat, players)}

JSON: {"thought":"your private reasoning (2–3 sentences)","target":"player_id"}`,
    },
  ]

  const raw = await callLLM(wolf.model, messages)
  const parsed = await safeJSON(raw, { thought: "Choosing a target.", target: fallbackTarget })
  const target = nonWolves.find((p) => p.id === parsed.target)?.id ?? fallbackTarget

  send({
    type: "statement",
    player: wolf.id,
    text: "…",
    thought: parsed.thought || "Selecting the kill target.",
    d: 1400,
  })

  return target
}

async function doctorTurn(
  doctor: Player,
  state: GameState,
  players: Player[],
  send: SendFn
): Promise<string> {
  const candidates = players.filter(
    (p) => state.alive.has(p.id) && p.id !== state.lastDoctorProtected
  )
  const fallback = candidates[0].id

  const messages: Message[] = [
    { role: "system", content: buildSystemPrompt(doctor, players) },
    {
      role: "user",
      content: `NIGHT ${state.round} — DOCTOR PROTECTION

Protect one player from wolves tonight.
${state.lastDoctorProtected ? `Cannot re-protect ${pname(state.lastDoctorProtected, players)} (last night's choice).` : ""}
Candidates: ${candidates.map((p) => `${p.name} [id:${p.id}]`).join(", ")}

Public chat:
${chatLog(state.publicChat, players)}

JSON: {"thought":"reasoning (2–3 sentences)","protect":"player_id"}`,
    },
  ]

  const raw = await callLLM(doctor.model, messages)
  const parsed = await safeJSON(raw, { thought: "Protecting someone.", protect: fallback })
  const protect = candidates.find((p) => p.id === parsed.protect)?.id ?? fallback

  send({
    type: "statement",
    player: doctor.id,
    text: "…",
    thought: parsed.thought || "Deciding who to guard.",
    d: 1400,
  })

  return protect
}

async function seerTurn(
  seer: Player,
  state: GameState,
  players: Player[],
  send: SendFn
): Promise<void> {
  const uninvestigated = players.filter(
    (p) =>
      state.alive.has(p.id) &&
      p.id !== seer.id &&
      !state.seerKnowledge.has(p.id)
  )
  if (uninvestigated.length === 0) return

  const known =
    Array.from(state.seerKnowledge.entries())
      .map(([id, r]) => `${pname(id, players)}=${r}`)
      .join(", ") || "none"

  const messages: Message[] = [
    { role: "system", content: buildSystemPrompt(seer, players) },
    {
      role: "user",
      content: `NIGHT ${state.round} — SEER INVESTIGATION

Already investigated: ${known}
Can investigate now: ${uninvestigated.map((p) => `${p.name} [id:${p.id}]`).join(", ")}

Public chat:
${chatLog(state.publicChat, players)}

JSON: {"thought":"reasoning (2–3 sentences)","investigate":"player_id"}`,
    },
  ]

  const raw = await callLLM(seer.model, messages)
  const parsed = await safeJSON(raw, { thought: "Investigating.", investigate: uninvestigated[0].id })
  const target = uninvestigated.find((p) => p.id === parsed.investigate)?.id ?? uninvestigated[0].id
  const targetPlayer = players.find((p) => p.id === target)!

  state.seerKnowledge.set(target, targetPlayer.role)

  const reveal = `The Seer learns: ${targetPlayer.name.toUpperCase()} is a ${targetPlayer.role.toUpperCase()}.`

  send({
    type: "statement",
    player: seer.id,
    text: "…",
    thought: `${parsed.thought || "Investigating..."} → ${reveal}`,
    d: 1400,
  })

  send({ type: "system", text: reveal, d: 1000 })
}

// ── Day statement ─────────────────────────────────────────────────────────

async function dayStatement(
  player: Player,
  state: GameState,
  players: Player[],
  send: SendFn
): Promise<void> {
  let privateInfo = ""
  if (player.role === "seer" && state.seerKnowledge.size > 0) {
    const k = Array.from(state.seerKnowledge.entries())
      .map(([id, r]) => `${pname(id, players)}=${r}`)
      .join(", ")
    privateInfo = `\nYour seer intel: ${k}`
  } else if (player.role === "werewolf") {
    const alivePartners = players.filter(
      (p) => p.role === "werewolf" && p.id !== player.id && state.alive.has(p.id)
    )
    if (alivePartners.length) {
      privateInfo = `\nYour wolf partner(s): ${alivePartners.map((p) => p.name).join(", ")} — coordinate suspicion without being obvious.`
    }
  }

  const guidance =
    player.role === "werewolf"
      ? "Deflect suspicion, seem helpful, create doubt about others."
      : "Analyze statements, look for inconsistencies, share your deductions."

  const messages: Message[] = [
    { role: "system", content: buildSystemPrompt(player, players) },
    {
      role: "user",
      content: `DAY ${state.round} DISCUSSION

Public statements so far:
${chatLog(state.publicChat, players)}

Alive: ${aliveList(players, state.alive)}${privateInfo}

Make a concise public statement (1–3 sentences). ${guidance}

JSON: {"thought":"private reasoning (2–3 sentences)","speech":"what you say publicly"}`,
    },
  ]

  const raw = await callLLM(player.model, messages)
  const parsed = await safeJSON(raw, {
    thought: "Observing.",
    speech: "I am watching everyone carefully.",
  })

  const speech = parsed.speech || "I am watching everyone carefully."
  state.publicChat.push({ player: player.id, text: speech })

  send({
    type: "statement",
    player: player.id,
    text: speech,
    thought: parsed.thought || "Thinking...",
    d: 1600,
  })
}

// ── Vote ──────────────────────────────────────────────────────────────────

async function voteAction(
  player: Player,
  state: GameState,
  players: Player[],
  send: SendFn
): Promise<string> {
  const candidates = players.filter(
    (p) => state.alive.has(p.id) && p.id !== player.id
  )
  const fallback = candidates[0].id

  let privateInfo = ""
  if (player.role === "seer" && state.seerKnowledge.size > 0) {
    const k = Array.from(state.seerKnowledge.entries())
      .map(([id, r]) => `${pname(id, players)}=${r}`)
      .join(", ")
    privateInfo = `\nSeer intel: ${k}`
  } else if (player.role === "werewolf") {
    const partners = players
      .filter((p) => p.role === "werewolf" && p.id !== player.id && state.alive.has(p.id))
      .map((p) => p.name)
    if (partners.length) {
      privateInfo = `\nWolf partner(s): ${partners.join(", ")} — vote against a villager.`
    }
  }

  const messages: Message[] = [
    { role: "system", content: buildSystemPrompt(player, players) },
    {
      role: "user",
      content: `VOTE — Round ${state.round}

Full discussion:
${chatLog(state.publicChat, players)}

Vote to eliminate (not yourself):
${candidates.map((p) => `${p.name} [id:${p.id}]`).join(", ")}${privateInfo}

JSON: {"thought":"final reasoning (1–2 sentences)","vote":"player_id"}`,
    },
  ]

  const raw = await callLLM(player.model, messages)
  const parsed = await safeJSON(raw, { thought: "Voting.", vote: fallback })
  const voteTarget = candidates.find((p) => p.id === parsed.vote)?.id ?? fallback

  send({ type: "vote", voter: player.id, target: voteTarget, d: 700 })
  return voteTarget
}

// ── End game ──────────────────────────────────────────────────────────────

function resolveEnd(
  players: Player[],
  state: GameState,
  winner: "wolves" | "villagers"
): { mvp: string; summary: string[] } {
  let mvp: string

  if (winner === "wolves") {
    const liveWolves = players.filter(
      (p) => p.role === "werewolf" && state.alive.has(p.id)
    )
    mvp = liveWolves[0]?.id ?? players[0].id
  } else {
    // Prefer the seer if alive; else highest correct-vote count
    const seer = players.find((p) => p.role === "seer")
    if (seer && state.alive.has(seer.id)) {
      mvp = seer.id
    } else {
      let best = players[0].id
      let max = 0
      for (const [id, n] of state.correctVotes) {
        if (n > max) { max = n; best = id }
      }
      mvp = best
    }
  }

  const seer = players.find((p) => p.role === "seer")
  const doctor = players.find((p) => p.role === "doctor")

  const summary: string[] = []
  if (winner === "villagers") {
    summary.push(
      `The village prevailed in ${state.round} round${state.round !== 1 ? "s" : ""}. Every werewolf was eliminated through logic and deduction.`
    )
    if (seer && state.seerKnowledge.size > 0) {
      summary.push(
        `${seer.name} (Seer) provided decisive intelligence — ${state.seerKnowledge.size} investigation${state.seerKnowledge.size > 1 ? "s" : ""} across the game.`
      )
    }
    if (doctor) {
      summary.push(
        `${doctor.name} (Doctor) disrupted the wolves' strategy with timely protection choices.`
      )
    }
  } else {
    const liveWolves = players.filter(
      (p) => p.role === "werewolf" && state.alive.has(p.id)
    )
    summary.push(
      `The wolves dominated — achieving parity after ${state.round} round${state.round !== 1 ? "s" : ""}.`
    )
    summary.push(
      `${liveWolves.map((w) => w.name).join(" and ")} survived through misdirection and strategic voting.`
    )
  }
  summary.push(
    "Every statement, deduction, and vote in this game was generated live by real AI models."
  )

  return { mvp, summary }
}

// ── Main entry point ──────────────────────────────────────────────────────

/** Run a complete Werewolf game, streaming GameEvents to `send` as they happen. */
export async function runGame(players: Player[], send: SendFn): Promise<void> {
  const state: GameState = {
    alive: new Set(players.map((p) => p.id)),
    round: 0,
    publicChat: [],
    seerKnowledge: new Map(),
    lastDoctorProtected: null,
    correctVotes: new Map(),
  }

  const wolves = players.filter((p) => p.role === "werewolf")
  const seer = players.find((p) => p.role === "seer")
  const doctor = players.find((p) => p.role === "doctor")

  // Hard cap: 5 rounds to avoid infinite loops / runaway API usage
  for (let r = 0; r < 5; r++) {
    state.round++

    // ── Night ──────────────────────────────────────────────────────────
    send({ type: "phase", phase: "night", round: state.round, d: 1200 })
    send({
      type: "system",
      text:
        state.round === 1
          ? wolves.length > 1
            ? "The village sleeps. The wolves open their eyes."
            : "The village sleeps. The wolf opens its eyes."
          : "Night falls again. The shadows move.",
      d: 1000,
    })

    // Wolves choose kill target
    let killTarget: string | null = null
    const liveWolves = wolves.filter((w) => state.alive.has(w.id))

    if (liveWolves.length > 0) {
      killTarget = await wolfTurn(
        liveWolves[0],
        liveWolves[1]?.name ?? null,
        state,
        players,
        send
      )
      await sleep(1200)

      // Second wolf silently "agrees" (shows thought, no new target)
      if (liveWolves[1]) {
        send({
          type: "statement",
          player: liveWolves[1].id,
          text: "…",
          thought: `${liveWolves[0].name} has chosen ${pname(killTarget, players)}. Agreed — that is the right play.`,
          d: 1400,
        })
        await sleep(1200)
      }
    }

    // Doctor protects
    let protected_: string | null = null
    if (doctor && state.alive.has(doctor.id)) {
      protected_ = await doctorTurn(doctor, state, players, send)
      state.lastDoctorProtected = protected_
      await sleep(1200)
    }

    // Seer investigates
    if (seer && state.alive.has(seer.id)) {
      await seerTurn(seer, state, players, send)
      await sleep(1200)
    }

    // Apply night results
    const killed = killTarget && killTarget !== protected_
    if (killed) {
      state.alive.delete(killTarget!)
      const victim = players.find((p) => p.id === killTarget)!
      send({ type: "kill", player: killTarget!, cause: "wolves", d: 2000 })

      const w = checkWin(players, state.alive)
      if (w) {
        const { mvp, summary } = resolveEnd(players, state, w)
        send({ type: "end", winner: w, mvp, summary, d: 1000 })
        return
      }

      send({ type: "phase", phase: "day", round: state.round, d: 1200 })
      send({
        type: "system",
        text: `${state.round === 1 ? "Dawn." : "Morning breaks."} ${victim.name} did not survive the night. ${state.alive.size} remain.`,
        d: 1000,
      })
    } else if (killTarget && killTarget === protected_) {
      send({ type: "phase", phase: "day", round: state.round, d: 1200 })
      send({
        type: "system",
        text: `The Doctor's vigil holds. Everyone wakes unharmed. ${state.alive.size} remain.`,
        d: 1000,
      })
    } else {
      send({ type: "phase", phase: "day", round: state.round, d: 1200 })
      send({
        type: "system",
        text: `The night passes quietly. ${state.alive.size} remain.`,
        d: 1000,
      })
    }

    // ── Day ────────────────────────────────────────────────────────────
    const alive = players.filter((p) => state.alive.has(p.id))

    for (const player of alive) {
      await dayStatement(player, state, players, send)
      await sleep(1000)
    }

    // ── Vote ───────────────────────────────────────────────────────────
    send({ type: "phase", phase: "vote", round: state.round, d: 1000 })

    const votes = new Map<string, string>()
    for (const player of alive) {
      const v = await voteAction(player, state, players, send)
      votes.set(player.id, v)
      await sleep(800)
    }

    const eliminated = tallyVotes(votes, state.alive) ?? alive[0].id
    const voteCount = Array.from(votes.values()).filter((v) => v === eliminated).length

    send({
      type: "system",
      text: `The village has decided: ${voteCount} vote${voteCount !== 1 ? "s" : ""} against ${pname(eliminated, players)}.`,
      d: 1000,
    })

    // Track correct wolf votes for MVP calculation
    if (players.find((p) => p.id === eliminated)?.role === "werewolf") {
      for (const [voter, target] of votes) {
        if (target === eliminated) {
          state.correctVotes.set(voter, (state.correctVotes.get(voter) ?? 0) + 1)
        }
      }
    }

    state.alive.delete(eliminated)
    send({ type: "kill", player: eliminated, cause: "vote", d: 2000 })

    const w2 = checkWin(players, state.alive)
    if (w2) {
      const { mvp, summary } = resolveEnd(players, state, w2)
      send({ type: "end", winner: w2, mvp, summary, d: 1000 })
      return
    }
  }

  // Failsafe if game drags past 5 rounds
  const w = checkWin(players, state.alive) ?? "villagers"
  const { mvp, summary } = resolveEnd(players, state, w)
  send({ type: "end", winner: w, mvp, summary, d: 1000 })
}
